### ISSUE TITLE
Access to MRT PEER_INDEX_TABLE

### ISSUE THREAD

**Issue by zimage** [AlexForster/bgpdumpy#6]
It'd be helpful to be able to view the contents of the PEER_INDEX_TABLE when writing code to extract information for a specific peer. How would I access this data with your library?

**Comment by alexforster** [comment]
Sorry there's no documentation. This is a pretty low-level, 1:1 wrapper around `libbgpdump`.

PEER_INDEX_TABLE entries are modeled as `TableDumpV2PeerIndexTableEntry` objects: https://github.com/alexforster/bgpdumpy/blob/8bef7b13b827a48286e49e036144b025d8f5ce31/BGPDump.py#L199

Here's the basic traversal code

```python
from bgpdumpy import BGPDump, TableDumpV2

with BGPDump('latest-bview.gz') as bgp:
    for entry in bgp:
        assert isinstance(entry.body, TableDumpV2)
        for routeEntry in entry.body.routeEntries:
            peerIndexTableEntry = routeEntry.peer
            print('peer AS: {}'.format(peerIndexTableEntry.peerAS))
```

I find the easiest way to use this library is to use [a good Python debugger](https://www.jetbrains.com/pycharm/download/) and just step in and look around.

![Screen Shot 2019-09-02 at 8 41 56 PM](https://user-images.githubusercontent.com/104311/64138304-246d4080-cdc2-11e9-92b9-76b730db26d5.png)

**Comment by alexforster** [comment]
Follow-up: while I was looking at this section, I noticed the `peerIP` and `peerRouterID` attributes were returning the raw `struct in_addr *` objects instead of converting them, so [I just fixed that](https://github.com/alexforster/bgpdumpy/pull/7) and pushed v1.1.2.
